export enum TacticalCategory {
  ATTACKING_SHAPE = 'ATTACKING_SHAPE',
  DEFENSIVE_SHAPE = 'DEFENSIVE_SHAPE',
  TRANSITION = 'TRANSITION',
  PRESSING = 'PRESSING',
  FORMATION = 'FORMATION',
  SPATIAL_CONTROL = 'SPATIAL_CONTROL'
}

export enum ComplexityLevel {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED'
}

export enum RequiredOverlay {
  PASSING_LANES = 'PASSING_LANES',
  PRESSING_ZONES = 'PRESSING_ZONES',
  MOVEMENT_ARROWS = 'MOVEMENT_ARROWS',
  SPACE_CONTROL = 'SPACE_CONTROL',
  DEFENSIVE_LINES = 'DEFENSIVE_LINES'
}
